### ISSUE TITLE
Options to retrieve number of columns SELECT result?

### ISSUE THREAD

**Issue by pavel-odintsov** [valyala/tsvreader#1]
Hello!

Thank you for a great library! It handles tens of gigabytes without any problems :)

But I need little bit more information from tsvreader.Reader. Is it possible to get a number of rows in SELECT operation using it?

I'm trying to solve case when I received zero rows and need to apply custom logic.

**Comment by hagen1778** [comment]
It seems like `tsvreader` does sequential reads row-by-row and don't have info about total amount of rows.
Description of func `Next` says:
`
// Returns true if the next row does exist.
`
So if at the very beginning you've got a `false` result from calling `reader.Next()` - means there are no rows at all.

**Comment by pavel-odintsov** [comment]
Ah, yes. Makes sense.
